language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - if [[ $TRAVIS_PHP_VERSION != '7.2' && $TRAVIS_PHP_VERSION != '7.3' && $TRAVIS_PHP_VERSION != '7.4' ]]; then
      composer remove phpunit/phpunit --dev;
      composer require phpunit/phpunit:^4 --dev;
      ./legacy.sh;
    fi
  - "travis_retry composer self-update"
  - "travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist"

script:
  - if [[ $TRAVIS_PHP_VERSION != '7.2' && $TRAVIS_PHP_VERSION != '7.3' && $TRAVIS_PHP_VERSION != '7.4' ]]; then
      vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover;
    else
      vendor/bin/phpunit --configuration phpunit.legacy.xml --coverage-text --coverage-clover=coverage.clover;
    fi

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
