language: php
dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - LEGACY=false

jobs:
  include:
    - php: 5.4
      env:
        - LEGACY=true
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 5.5
      env: LEGACY=true
    - php: 5.6
      env: LEGACY=true
    - php: 7.0
      env: LEGACY=true
    - php: 7.1
      env: LEGACY=true

before_script:
  - if [[ $LEGACY == 'true' ]]; then
      composer remove phpunit/phpunit --dev;
      composer require phpunit/phpunit:^4 --dev;
      ./legacy.sh;
    fi
  - "travis_retry composer self-update"
  - "travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source"

script:
  - if [[ $LEGACY == 'true' ]]; then
      vendor/bin/phpunit --configuration phpunit.legacy.xml --coverage-text --coverage-clover=coverage.clover;
    else
      vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover;
    fi

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
